"""add phone number column

Revision ID: fdf344fd5738
Revises: dddc2d29dd61
Create Date: 2022-07-09 06:22:47.819177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fdf344fd5738"
down_revision = "dddc2d29dd61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
